export const MOVIE_FETCH_REQUESTED = 'MOVIE_FETCH_REQUESTED';
export const MOVIE_FETCH_SUCCEEDED = 'MOVIE_FETCH_SUCCEEDED';
export const MOVIE_FETCH_FAILED = 'MOVIE_FETCH_FAILED';

export const MOVIES_FETCH_REQUESTED = 'MOVIES_FETCH_REQUESTED';
export const MOVIES_FETCH_SUCCEEDED = 'MOVIES_FETCH_SUCCEEDED';
export const MOVIES_FETCH_FAILED = 'MOVIES_FETCH_FAILED';

export const MOVIE_ADD_FAVORITE = 'MOVIE_ADD_FAVORITE';
export const MOVIE_REMOVE_FAVORITE = 'MOVIE_REMOVE_FAVORITE';

export const PAGE_ITEMS = 10
